name: Deploy to Glitch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v1
      - uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.authToken }}'
          project-id: '${{ secrets.projectId }}'